# Generated by Django 4.2.1 on 2023-05-25 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pythonInter_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('about', models.CharField(max_length=150)),
                ('repository_link', models.URLField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
