# Generated by Django 4.2.1 on 2023-05-25 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pythonInter_app', '0002_projectplatform_user_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='userlist', to='pythonInter_app.projectplatform'),
            preserve_default=False,
        ),
    ]
